.PHONY: build dev soak stress test test-race test-release-build install-golangci-lint lint check

BIN ?= tgfile
GO ?= go
GOBIN ?= $(CURDIR)/bin
GOCACHE ?= $(CURDIR)/.cache/go-build
GOLANGCI_LINT_CACHE ?= $(CURDIR)/.cache/golangci-lint
GOLANGCI_LINT_VERSION ?= v2.11.4
GOLANGCI_LINT ?= $(GOBIN)/golangci-lint
SOAK_DURATION ?= 15m
SOAK_WORKERS ?= 4
SOAK_SEED ?=
SOAK_CLIENT_DELAY ?= 5ms
SOAK_BACKEND_DELAY ?= 5ms
STRESS_STEPS ?= 1,4,8,16,32
STRESS_STEP_DURATION ?= 1m
STRESS_RECOVERY_DURATION ?= 30s
STRESS_PROFILE ?= mixed
STRESS_MAX_ERROR_RATE ?= 0.01
STRESS_MAX_P99 ?= 5s
STRESS_OPERATION_TIMEOUT ?= 15s
STRESS_MUTATION_INTERVAL ?= 1000
STRESS_SEED ?=
STRESS_CLIENT_DELAY ?= 0s
STRESS_BACKEND_DELAY ?= 0s

build:
	GOCACHE=$(GOCACHE) $(GO) build -o $(BIN) ./cmd

dev:
	TGFILE_DEV_GO="$(GO)" TGFILE_DEV_CONFIG="$(CONFIG)" ./scripts/dev.sh

soak:
	TGFILE_SOAK_DURATION="$(SOAK_DURATION)" TGFILE_SOAK_WORKERS="$(SOAK_WORKERS)" \
		TGFILE_SOAK_SEED="$(SOAK_SEED)" TGFILE_SOAK_CLIENT_DELAY="$(SOAK_CLIENT_DELAY)" \
		TGFILE_SOAK_BACKEND_DELAY="$(SOAK_BACKEND_DELAY)" GOCACHE="$(GOCACHE)" $(GO) run ./tools/soak soak

stress:
	TGFILE_STRESS_STEPS="$(STRESS_STEPS)" TGFILE_STRESS_STEP_DURATION="$(STRESS_STEP_DURATION)" \
		TGFILE_STRESS_RECOVERY_DURATION="$(STRESS_RECOVERY_DURATION)" \
		TGFILE_STRESS_PROFILE="$(STRESS_PROFILE)" \
		TGFILE_STRESS_MAX_ERROR_RATE="$(STRESS_MAX_ERROR_RATE)" \
		TGFILE_STRESS_MAX_P99="$(STRESS_MAX_P99)" \
		TGFILE_STRESS_OPERATION_TIMEOUT="$(STRESS_OPERATION_TIMEOUT)" \
		TGFILE_STRESS_MUTATION_INTERVAL="$(STRESS_MUTATION_INTERVAL)" \
		TGFILE_STRESS_SEED="$(STRESS_SEED)" TGFILE_STRESS_CLIENT_DELAY="$(STRESS_CLIENT_DELAY)" \
		TGFILE_STRESS_BACKEND_DELAY="$(STRESS_BACKEND_DELAY)" \
		GOCACHE="$(GOCACHE)" $(GO) run ./tools/soak stress

test:
	GOCACHE=$(GOCACHE) $(GO) test -count=1 ./...

test-race:
	GOCACHE=$(GOCACHE) $(GO) test -count=1 -race ./...

test-release-build:
	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOCACHE=$(GOCACHE) $(GO) build -o /dev/null ./cmd
	CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 GOCACHE=$(GOCACHE) $(GO) build -o /dev/null ./cmd
	CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOCACHE=$(GOCACHE) $(GO) build -o /dev/null ./cmd

install-golangci-lint:
	GOBIN=$(GOBIN) GOCACHE=$(GOCACHE) $(GO) install \
		github.com/golangci/golangci-lint/v2/cmd/golangci-lint@$(GOLANGCI_LINT_VERSION)

lint:
	PATH=$(dir $(GO)):$$PATH GOCACHE=$(GOCACHE) GOLANGCI_LINT_CACHE=$(GOLANGCI_LINT_CACHE) \
		$(GOLANGCI_LINT) run --config .golangci.yml ./...

check:
	test -z "$$($(GO)fmt -l .)"
	$(GO) vet ./...
	$(MAKE) test
	$(MAKE) test-race
	$(MAKE) test-release-build
	$(MAKE) lint
